apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
  namespace: toggle-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::576394965690:role/togglemaster-eks-analytics-service-role