apiVersion: batch/v1
kind: Job
metadata:
  name: targeting-db-create
  namespace: toggle-prod
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"

spec:
  backoffLimit: 3

  template:
    metadata:
      labels:
        app: targeting-db-create

    spec:
      restartPolicy: OnFailure

      containers:
        - name: postgres-create-db
          image: postgres:16

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: flag-secret
                  key: DATABASE_URL

          command:
            - /bin/sh
            - -c
            - |
              set -e

              echo "Verificando se targeting_db existe..."

              DB_EXISTS=$(psql "$DATABASE_URL" -tAc \
                "SELECT 1 FROM pg_database WHERE datname = 'targeting_db';")

              if [ "$DB_EXISTS" = "1" ]; then
                echo "targeting_db já existe."
              else
                echo "targeting_db não existe. Criando..."

                psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c \
                  "CREATE DATABASE targeting_db;"

                echo "targeting_db criado com sucesso."
              fi