apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
  namespace: toggle-prod

data:
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/708993007071/evaluation-analytics-queue"