apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: toggle-prod
type: Opaque
stringData:
  DATABASE_URL: "postgres://auth_user:3hP5b4pvqA5r5Z7m@rds-auth.c3qk0hy22u5d.us-east-1.rds.amazonaws.com:5432/auth_db?sslmode=require"
  MASTER_KEY: "admin-secreto-123"


