apiVersion: v1
kind: ServiceAccount
metadata:
  name: evaluation-api-key-bootstrap
  namespace: toggle-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::576394965690:role/togglemaster-eks-evaluation-bootstrap-role