apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-config
  namespace: toggle-prod

data:
  PORT: "8004"
  REDIS_URL: "redis://evaluation-service-redis.yumvds.0001.use1.cache.amazonaws.com:6379"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
  AWS_REGION: "us-east-1"