apiVersion: apps/v1
kind: Deployment

metadata:
  name: targeting-service
  namespace: toggle-prod

spec:

  replicas: 1

  selector:
    matchLabels:
      app: targeting-service


  template:

    metadata:
      labels:
        app: targeting-service


    spec:

      containers:

        - name: targeting-service

          image: 784380251158.dkr.ecr.us-east-1.amazonaws.com/togglemaster/targeting-service:latest

          imagePullPolicy: Always


          ports:

            - containerPort: 8003


          envFrom:

            - configMapRef:
                name: targeting-config

            - secretRef:
                name: targeting-secret


          resources:

            requests:
              cpu: "50m"
              memory: "64Mi"

            limits:
              cpu: "250m"
              memory: "256Mi"



          readinessProbe:

            httpGet:
              path: /health
              port: 8003

            initialDelaySeconds: 10
            periodSeconds: 5



          livenessProbe:

            httpGet:
              path: /health
              port: 8003

            initialDelaySeconds: 30
            periodSeconds: 10