apiVersion: apps/v1
kind: Deployment

metadata:
  name: evaluation-service
  namespace: toggle-prod

spec:

  replicas: 1

  selector:
    matchLabels:
      app: evaluation-service


  template:

    metadata:
      labels:
        app: evaluation-service


    spec:

      containers:

        - name: evaluation-service

          image: 708993007071.dkr.ecr.us-east-1.amazonaws.com/evaluation-service:latest

          imagePullPolicy: Always


          ports:

            - containerPort: 8004


          envFrom:

            - configMapRef:
                name: evaluation-config

            - secretRef:
                name: evaluation-secret


          resources:

            requests:
              cpu: "50m"
              memory: "64Mi"

            limits:
              cpu: "250m"
              memory: "256Mi"



          readinessProbe:

            httpGet:
              path: /health
              port: 8004

            initialDelaySeconds: 10
            periodSeconds: 5



          livenessProbe:

            httpGet:
              path: /health
              port: 8004

            initialDelaySeconds: 30
            periodSeconds: 10