apiVersion: v1
kind: Secret
metadata:
  name: targeting-secret
  namespace: toggle-prod
type: Opaque
stringData:
  DATABASE_URL: postgres://flag_user:XmJeaTBW65zjCEqD@rds-flag.cc7ss20oaani.us-east-1.rds.amazonaws.com:5432/targeting_db?sslmode=require